server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

